<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=9"/>
        <title>Tizen Native API: Account Manager</title>

        <link href="tabs.css" rel="stylesheet" type="text/css"/>
        <link href="doxygen_html_stylesheet.css" rel="stylesheet" type="text/css" />
        <link href="navtree.css" rel="stylesheet" type="text/css"/>
       
        <script type="text/javascript" src="jquery.js"></script>
        <script type="text/javascript" src="resize.js"></script>
        <script type="text/javascript" src="navtree.js"></script>
        <script type="text/javascript">
            $(document).ready(initResizable);
        </script>
         <link href="/css/search.css" rel="stylesheet">
        <script type="text/javascript" src="search/search.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                if ($('.searchresults').length > 0) {
                    searchBox.DOMSearchField().focus();
                }
            });
        </script>
        <link rel="search" href="search-opensearch.php?v=opensearch.xml" type="application/opensearchdescription+xml" title="Tizen Native API"/>

    </head>
    <body>
        <div id="top"><!-- do not remove this div! -->


            <div id="titlearea">
                <table cellspacing="0" cellpadding="0">
                    <tbody>
                        <tr style="height: 56px;">


                            <td style="padding-left: 0.5em;">
                                <div id="projectname">Tizen Native API
                                    &#160;<span id="projectnumber">4.0</span>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <!-- Generated by Doxygen 1.7.6.1 -->
            <script type="text/javascript">
                var searchBox = new SearchBox("searchBox", "search", false, 'Search');
            </script>
            <script type="text/javascript" src="dynsections.js"></script>
            <div id="navrow1" class="tabs">
                <ul class="tablist">
                    <li><a href="index.html"><span>The&#160;Basics&#160;of&#160;Tizen&#160;Native&#160;API&#160;Reference</span></a></li>
                    <li><a href="modules.html"><span>Native&#160;API&#160;Reference</span></a></li>
                    <li>
                        <div id="MSearchBox" class="MSearchBoxInactive">
                            <div class="left">
                                <form id="FSearchBox" action="search.php" method="get">
                                    <img id="MSearchSelect" src="search/mag.png" alt=""/>
                                    <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                                           onfocus="searchBox.OnSearchFieldFocus(true)" 
                                           onblur="searchBox.OnSearchFieldFocus(false)"/>
                                </form>
                            </div><div class="right"></div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div id="side-nav" class="ui-resizable side-nav-resizable">
            <div id="nav-tree">
                <div id="nav-tree-contents">
                </div>
            </div>
            <div id="splitbar" style="-moz-user-select:none;" 
                 class="ui-resizable-handle">
            </div>
        </div>
        <script type="text/javascript">
            initNavTree('modules.html', '');
        </script>

        <?php
        require $_SERVER['DOCUMENT_ROOT'] . '/utils/common.php';

        $search_start = isset($_GET['start']) ? $_GET['start'] : 0;
        $search_pageSize = isset($_GET['pageSize']) ? $_GET['pageSize'] : 10;
        $search_text = $_GET['search'];

        $current_page = intval($search_start / $search_pageSize) + 1;

        $request_uri = $_SERVER['REQUEST_URI'];
        $url_search_base = explode('?', $request_uri)[0];

        $url = "http://td-prd-crawler-elb-1900134565.us-west-2.elb.amazonaws.com/api/v1/docs/search?start=" . $search_start . "&pageSize=10";
//        $url = "http://10.10.11.193:8080/api/v1/docs/search?start=" . $search_start . "&pageSize=10";

        $content = '{
                                "queryText": "' . $search_text . '" ,
                                "terms": [
                                  ["domain:docs.tizen.org"],
                                  ["link:docs.tizen.org/application/native/api", "link:docs.tizen.org/application/web/api", "link:docs.tizen.org/application/dotnet/api"]
                                 ]
                              }';

        $curl = curl_init($url);
        curl_setopt($curl, CURLOPT_HEADER, false);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_HTTPHEADER, array("Content-type: application/json"));
        curl_setopt($curl, CURLOPT_POST, true);
        curl_setopt($curl, CURLOPT_POSTFIELDS, $content);

        $json_response = curl_exec($curl);
        $status = curl_getinfo($curl, CURLINFO_HTTP_CODE);

        curl_close($curl);

        $response = json_decode($json_response, true);

        $page_size = 10;
        $page_quantity = intval($response['searchInformation']['totalResults'] / $page_size) +1;
        ?>

        <div id="doc-content">
            <div class="tbl-search">
                <div class="txt-display">Total of <em><?php echo $response['searchInformation']['totalResults'] ?></em> search results for <em>"<?php echo $search_text ?></em>"</div>
            </div> 
            <div class="contents">
                <?php
                if ($response['items'] != null) {
                    foreach ($response['items'] as $item => $value) {
                        ?>
                        <li class="search-result">
                            <div class="td-wrap-result">
                                <h3 class="title"><a href="<?php echo $value['link']; ?>"><?php echo $value['htmlTitle']; ?></a></h3>
                            </div>
                            <div class="search-snippet-info">
                                <p class="search-snippet"><?php echo $value['htmlSnippet']; ?></p>
                                <a href="<?php echo $value['link']; ?>"><?php echo $value['htmlLink'] ?></a>
                            </div>
                        </li>
                        <?php
                    }
                } else {
                    echo 'No result found';
                }
                ?>
            </div>
            <div id="paginationBar" class="pageNumber mt20">
                <?php
                if ($current_page == 1) {
                    ?>
                <a style="border: none" class="prev"><img src="/images/ico_arr_prev.gif" alt="go prev"></a>
                    <?php
                } else {
                    ?>
                    <a style="border: none" href=<?php echo $url_search_base;?>?search=<?php echo $search_text; ?>&start=<?php echo (($page_size * ($current_page - 2)) + 1) ?>&pageSize=<?php echo $page_size ?> class="prev"><img src="/images/ico_arr_prev.gif" alt="go prev"></a>
                    <?php
                }
                ?>

                <span class="page">
                    <?php
                    $index_multi = intval(($current_page - 1) / 10);
                    $end_point = 10 + 10 * $index_multi;
                    if ($page_quantity < 10 + 10 * $index_multi) {
                        $end_point = $page_quantity;
                    }

                    for ($i = 1 + 10 * $index_multi; $i <= $end_point; $i++) {
                        if ($i != $current_page) {
                            ?>
                            <a href=<?php echo $url_search_base;?>?search=<?php echo $search_text; ?>&start=<?php echo (($page_size * ($i - 1)) + 1) ?>&pageSize=<?php echo $page_size ?>><?php echo $i ?></a>
                            <?php
                        } else {
                            ?>
                            <a href=<?php echo $url_search_base;?>?search=<?php echo $search_text; ?>&start=<?php echo (($page_size * ($i - 1)) + 1) ?>&pageSize=<?php echo $page_size ?>><strong><?php echo $i ?></strong></a>
                            <?php
                        }
                        ?>

                        <?php
                    }
                    ?>
                </span>
                <?php
                if ($current_page == $page_quantity) {
                    ?>
                    <a style="border: none" class="next"><img src="/images/ico_arr_next.gif" alt="go next"></a></div>
                <?php
            } else {
                ?>
                <a style="border: none" href=<?php echo $url_search_base;?>?search=<?php echo $search_text; ?>&start=<?php echo (($page_size * ($current_page)) + 1) ?>&pageSize=<?php echo $page_size ?> class="next"><img src="/images/ico_arr_next.gif" alt="go next"></a>
            </div>
            <?php
        }
        ?>
        </div>
        <hr size="1">

    </body>
</html>
